create or replace TABLE tips_test_transform.customer (
	COBID NUMBER(8,0),
	C_NAME VARCHAR(25) NOT NULL,
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(12,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117),
	primary key (C_NAME)
);