create or replace TABLE tips_test_dimension.customer (
	CUSTOMER_KEY NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(25),
	CUSTOMER_ADDRESS VARCHAR(40),
	CUSTOMER_PHONE VARCHAR(15),
	CUSTOMER_MARKET_SEGMENT VARCHAR(10),
	CUSTOMER_COMMENT VARCHAR(117),
	COUNTRY VARCHAR(25),
	REGION VARCHAR(25),
	BINARY_CHECK_SUM NUMBER(38,0) AS (HASH(CUSTOMER_NAME, CUSTOMER_ADDRESS, CUSTOMER_PHONE, CUSTOMER_MARKET_SEGMENT, CUSTOMER_COMMENT, COUNTRY, REGION))
);