CREATE TABLE IF NOT EXISTS PROCESS_LOG (
    PROCESS_LOG_ID                      NUMBER(38,0) NOT NULL PRIMARY KEY DEFAULT PROCESS_LOG_SEQ.NEXTVAL,
    PROCESS_NAME                        VARCHAR(100) NOT NULL,
    PROCESS_LOG_CREATED_AT              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PROCESS_START_TIME                  TIMESTAMP,
    PROCESS_END_TIME                    TIMESTAMP,
    PROCESS_ELAPSED_TIME_IN_SECONDS     INTEGER,
    EXECUTE_FLAG                        VARCHAR2(1) NOT NULL DEFAULT 'Y',
    STATUS                              VARCHAR2(100) NOT NULL,
    ERROR_MESSAGE                       VARCHAR,
    LOG_JSON                            VARIANT NOT NULL
);