CREATE OR REPLACE TABLE process_cmd (
    process_id                          NUMBER(38,0) NOT NULL,
    process_cmd_id                      NUMBER(38,0) NOT NULL,
    parent_process_cmd_id               VARCHAR NOT NULL DEFAULT 'NONE',
    cmd_type                            VARCHAR(30) NOT NULL,
    cmd_src                             VARCHAR,
    cmd_tgt                             VARCHAR NOT NULL,
    cmd_where                           VARCHAR,
    cmd_binds                           VARCHAR,
    refresh_type                        VARCHAR(10),
    business_key                        VARCHAR(100),
    merge_on_fields                     VARCHAR,
    generate_merge_matched_clause       VARCHAR(1),
    generate_merge_non_matched_clause   VARCHAR(1),
    additional_fields                   VARCHAR,
    copy_auto_mapping                   VARCHAR(1),
    copy_into_force                     VARCHAR(1),
    temp_table                          VARCHAR(1),
    cmd_pivot_by                        VARCHAR,
    cmd_pivot_field                     VARCHAR,
    dq_type                             VARCHAR(100),
    cmd_external_call                   VARCHAR,
    file_format_name                    VARCHAR,
    copy_into_file_paritition_by        VARCHAR,
    warehouse_size                      VARCHAR,
    active                              VARCHAR(1) DEFAULT 'Y'
);
