create or replace view tips_test_transform.vw_customer_with_lookups(
	COBID,
	C_NAME,
	C_ADDRESS,
	C_NATIONKEY,
	C_PHONE,
	C_ACCTBAL,
	C_MKTSEGMENT,
	C_COMMENT,
	N_NAME,
	N_NATIONKEY,
	R_NAME,
	R_REGION_KEY
) as
SELECT c.*, n.N_NAME, n.N_NATIONKEY , r.R_NAME, n.N_REGIONKEY r_region_key
  FROM "TIPS_TEST_TRANSFORM".CUSTOMER c
  LEFT JOIN "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."NATION" n ON c.C_NATIONKEY = n.N_NATIONKEY 
  LEFT JOIN "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."REGION" r ON n.N_REGIONKEY = r.R_REGIONKEY;